databases:
  - name: app
    databaseName: app_production
    user: postgres

services:
  - type: web
    name: budget_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false